export const EDIT_RESUME_FIRSTNAME = 'EDIT_RESUME_FIRSTNAME';
export const EDIT_RESUME_LASTNAME = 'EDIT_RESUME_LASTNAME';
export const EDIT_RESUME_PHONE = 'EDIT_RESUME_PHONE';
export const EDIT_RESUME_TITLE = 'EDIT_RESUME_TITLE';
export const EDIT_RESUME_CITY = 'EDIT_RESUME_CITY';
export const EDIT_RESUME_STATE = 'EDIT_RESUME_STATE';
export const EDIT_RESUME_ICON = 'EDIT_RESUME_ICON';
export const NEW_RESUME_ICON = 'NEW_RESUME_ICON';
